class ShoesFrameInterface:

    def hide_colors(self) -> None:
        ...

    def show_colors(self) -> None:
        ...

    def set_selected_size_frame(self, size_frame) -> None:
        ...

    def get_selected_size_frame(self):
        ...

    def del_selected_size_frame(self) -> None:
        ...

    def edit_size_frame(self, size_frame) -> None:
        ...
